ARDUINO_DIR=/usr/share/arduino

BOARD_TAG=atmega328
ARDUINO_PORT=/dev/ttyUSB1

BOARD_TAG=atmega328
MCU=atmega328
F_CPU=16000000L
ARDUINO_PORT=/dev/ttyUSB1

ARDUINO_LIBS = JeeLib

include /usr/share/arduino/Arduino.mk

AVRDUDE_COM_OPTS=-q -V -p m328p
